name: Daily Inventory Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"  # Runs every day at 11:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 openpyxl requests

      - name: Run scraper
        run: python update_locator_inventory.py --temp

      - name: Upload test output
        uses: actions/upload-artifact@v3
        with:
          name: ScrapedInventory
          path: Locator_Detail_Test.xlsx
