name: Daily Inventory Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (test mode)
        run: python update_locator_inventory.py --temp

      - name: Upload scraped inventory
        uses: actions/upload-artifact@v3
        with:
          name: scraped-inventory
          path: Locator_Detail_Test.xlsx
