name: Daily Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9:00 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 lxml openpyxl requests

      - name: Run scraper
        run: python Daily\ Scrape.py

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: locator-detail
          path: Locator_Detail_Updated.xlsx
